addpath('tapas/HGF')
inputs = Task2_2(2.5,-4,-6,0,0,0);
u= inputs(:,1);

sim = tapas_simModel(u,...
'tapas_hgf_binary',...
[NaN 0 1 NaN 0 1 NaN 0 0 0 2.5 NaN -4 -6],...
'tapas_unitsq_sgm',...
5);

est = tapas_fitModel(sim.y,...
                     sim.u,...
                     'tapas_hgf_binary_config',...
                     'tapas_unitsq_sgm_config',...
                     'tapas_quasinewton_optim_config')
                 
tapas_fit_plotCorr(est)
                 
